# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: GreenYogaInc.PDFLiteViewer
PackageVersion: 1.0.12
MinimumOSVersion: 10.0.19041.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: PdfLiteViewer.exe
    PortableCommandAlias: PdfLiteViewer
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/greenyogainc/pdf-lite-viewer/releases/download/v1.0.12/PdfLiteViewer-1.0.12-win-x64.zip
    InstallerSha256: CF041717B44BBBA786339170A0699DDD900FA67727266EFBAA8FBB3ABF97DBC7
  - Architecture: arm64
    InstallerUrl: https://github.com/greenyogainc/pdf-lite-viewer/releases/download/v1.0.12/PdfLiteViewer-1.0.12-win-arm64.zip
    InstallerSha256: 116BE31F52A1A62BDAA8D3354B5433E0F32E0E4E2BCED2DE4D8F288825CC62DF
ManifestType: installer
ManifestVersion: 1.6.0