# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: GreenYogaInc.PDFLiteViewer
PackageVersion: 1.0.10
MinimumOSVersion: 10.0.19041.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: PdfLiteViewer.exe
    PortableCommandAlias: PdfLiteViewer
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/greenyogainc/pdf-lite-viewer/releases/download/v1.0.10/PdfLiteViewer-1.0.10-win-x64.zip
    InstallerSha256: 7347091A47980048209B37159F427578810188F47A728C13D57EE9FC31F28C5B
  - Architecture: arm64
    InstallerUrl: https://github.com/greenyogainc/pdf-lite-viewer/releases/download/v1.0.10/PdfLiteViewer-1.0.10-win-arm64.zip
    InstallerSha256: 29AE1410ED50975116A3292C51384DEC9EAE850D7364A90A47DF194AE3664DC5
ManifestType: installer
ManifestVersion: 1.6.0